export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';
export const UPDATE_TOTAL_PRICE ='UPDATE_TOTAL_PRICE';
export const REMOVE_PRODUCT ='REMOVE_PRODUCT';
export const GET_PRODUCTS='GET_PRODUCTS';

